/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/acAUi3j4n0P
* Documentation: https://v0.dev/docs#integrating-with-your-app
*/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardContent } from "@/components/ui/card"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import Image from "next/image"
import { BarChart2, Zap, Users, Shield, ArrowRight, TrendingUp, DollarSign, Globe, Lock, BrainCircuit, CheckCircle } from "lucide-react"
import { Badge } from "@/components/ui/badge"
import { MobileNav } from "@/components/mobile-nav"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-[100dvh] bg-background font-body">
      <header className="px-4 lg:px-6 h-16 flex items-center bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <Link href="#" className="flex items-center justify-center" prefetch={false}>
          <BarChart2 className="h-6 w-6 text-primary" />
          <span className="sr-only">PollPulse</span>
        </Link>
        <nav className="ml-auto hidden lg:flex gap-4 sm:gap-6">
          <Link href="#features" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            For Brands
          </Link>
          <Link href="#how-it-works" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            For Consumers
          </Link>
          <Link href="#pricing" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Pricing
          </Link>
           <Link href="#testimonials" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Testimonials
          </Link>
        </nav>
        <div className="ml-auto lg:hidden">
          <MobileNav />
        </div>
        <div className="hidden lg:flex items-center gap-4 ml-6">
            <Button variant="ghost" asChild><Link href="/login">Sign In</Link></Button>
            <Button asChild><Link href="/signup">Get Started</Link></Button>
        </div>
      </header>
      <main className="flex-1">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
          <div className="container px-4 md:px-6">
            <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-4">
                   <Badge variant="outline" className="py-2 px-4 rounded-full text-lg text-primary border-primary/50">Real People. Real Opinions. Real Time.</Badge>
                  <h1 className="text-4xl font-bold font-headline tracking-tighter text-foreground sm:text-5xl xl:text-6xl/none">
                    Pulse Check Your Market™
                  </h1>
                  <p className="max-w-[600px] text-muted-foreground md:text-xl">
                    Get instant consumer opinions and real-time market insights with lightning-fast polls - results in minutes, not days.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Button asChild size="lg">
                    <Link href="/signup">
                      Launch Your First Poll
                    </Link>
                  </Button>
                   <Button asChild size="lg" variant="outline">
                    <Link href="/signup">
                      Start Earning
                    </Link>
                  </Button>
                </div>
              </div>
              <Image
                src="https://images.unsplash.com/photo-1712903900648-3d1c94cfc487?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxNnx8cG9sbHxlbnwwfHx8fDE3NTMyNTUzOTd8MA&ixlib=rb-4.1.0&q=80&w=1080"
                width="600"
                height="600"
                alt="Hero"
                data-ai-hint="market trends"
                className="mx-auto aspect-square overflow-hidden rounded-xl object-cover sm:w-full lg:order-last"
              />
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted/50">
            <div className="container px-4 md:px-6">
                <div className="flex flex-col items-center justify-center space-y-4 text-center">
                    <h2 className="text-3xl font-bold font-headline tracking-tighter sm:text-4xl">Trusted by 500+ Brands Worldwide</h2>
                    <p className="max-w-[600px] text-muted-foreground">and 50,000+ Active Poll Takers</p>
                </div>
                <div className="mx-auto mt-12 grid grid-cols-2 gap-8 sm:grid-cols-3 md:grid-cols-6">
                    <div className="flex justify-center items-center">
                        <Image src="https://placehold.co/120x60.png" alt="Brand Logo" width={120} height={60} data-ai-hint="company logo" className="grayscale opacity-60" />
                    </div>
                     <div className="flex justify-center items-center">
                        <Image src="https://placehold.co/120x60.png" alt="Brand Logo" width={120} height={60} data-ai-hint="company logo" className="grayscale opacity-60" />
                    </div>
                     <div className="flex justify-center items-center">
                        <Image src="https://placehold.co/120x60.png" alt="Brand Logo" width={120} height={60} data-ai-hint="company logo" className="grayscale opacity-60" />
                    </div>
                     <div className="flex justify-center items-center">
                        <Image src="https://placehold.co/120x60.png" alt="Brand Logo" width={120} height={60} data-ai-hint="company logo" className="grayscale opacity-60" />
                    </div>
                     <div className="flex justify-center items-center">
                        <Image src="https://placehold.co/120x60.png" alt="Brand Logo" width={120} height={60} data-ai-hint="company logo" className="grayscale opacity-60" />
                    </div>
                    <div className="flex justify-center items-center">
                        <Image src="https://placehold.co/120x60.png" alt="Brand Logo" width={120} height={60} data-ai-hint="company logo" className="grayscale opacity-60" />
                    </div>
                </div>
            </div>
        </section>

        <section id="features" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <Badge variant="outline" className="py-2 px-4 text-xl">For Brands</Badge>
                <h2 className="text-3xl font-bold font-headline tracking-tighter sm:text-5xl">Why Choose PollPulse?</h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Our platform is designed to provide you with accurate, real-time data from a verified human panel.
                </p>
              </div>
            </div>
            <div className="mx-auto grid max-w-5xl items-start gap-8 sm:grid-cols-2 md:gap-12 lg:grid-cols-3 lg:max-w-none mt-12">
              <div className="grid gap-2">
                <Zap className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold font-headline">Lightning Fast Results</h3>
                <p className="text-muted-foreground">
                  Get insights in 10 minutes, not 10 days. No minimums, pay only for the responses you get.
                </p>
              </div>
               <div className="grid gap-2">
                <Users className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold font-headline">Laser Targeting</h3>
                <p className="text-muted-foreground">
                  Reach exactly who you need with advanced demographic and behavioral filters.
                </p>
              </div>
              <div className="grid gap-2">
                <TrendingUp className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold font-headline">Real-Time Dashboard</h3>
                <p className="text-muted-foreground">
                  Access live dashboards displaying response rates and deep analytics to make informed decisions instantly.
                </p>
              </div>
              <div className="grid gap-2">
                <Lock className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold font-headline">Fraud-Free Guarantee</h3>
                <p className="text-muted-foreground">
                  Our AI-powered bot detection ensures a 99.9% verified human panel for data you can trust.
                </p>
              </div>
              <div className="grid gap-2">
                <BrainCircuit className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold font-headline">AI-Powered Insights</h3>
                <p className="text-muted-foreground">
                  Go beyond the numbers with AI-generated summaries and trend analysis to uncover deeper meaning.
                </p>
              </div>
              <div className="grid gap-2">
                <Globe className="h-8 w-8 text-primary" />
                <h3 className="text-xl font-bold font-headline">Global Reach</h3>
                <p className="text-muted-foreground">
                  Tap into a diverse, global audience across 50+ countries for a worldwide perspective.
                </p>
              </div>
            </div>
          </div>
        </section>

        <section id="how-it-works" className="w-full py-12 md:py-24 lg:py-32 bg-muted/50">
           <div className="container grid items-center gap-6 px-4 md:px-6 lg:grid-cols-2 lg:gap-12">
                <div className="space-y-4">
                    <Badge variant="outline" className="py-2 px-4 text-xl">For Consumers</Badge>
                    <h2 className="text-3xl font-bold font-headline tracking-tighter sm:text-4xl">Turn Your Opinions Into Cash</h2>
                    <p className="max-w-[600px] text-muted-foreground md:text-xl/relaxed">
                        Answering quick polls on PollPulse is the easiest way to earn extra cash during your free time. No long, boring surveys—just quick questions that respect your time.
                    </p>
                    <ul className="grid gap-4">
                        <li className="flex items-center gap-3">
                            <CheckCircle className="h-6 w-6 text-primary" />
                            <span className="font-medium">Instant Payouts to PayPal</span>
                        </li>
                        <li className="flex items-center gap-3">
                            <CheckCircle className="h-6 w-6 text-primary" />
                            <span className="font-medium">30-second polls, not 30-minute surveys</span>
                        </li>
                        <li className="flex items-center gap-3">
                            <CheckCircle className="h-6 w-6 text-primary" />
                            <span className="font-medium">Your privacy is always protected</span>
                        </li>
                    </ul>
                     <div className="flex flex-col gap-2 min-[400px]:flex-row">
                        <Button asChild size="lg">
                            <Link href="/signup">Download App & Start Earning</Link>
                        </Button>
                    </div>
                </div>
                 <Image
                    src="https://images.unsplash.com/photo-1483478550801-ceba5fe50e8e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHxkaWdpdGFsJTIwcGF5bWVudHxlbnwwfHx8fDE3NTMyNTU1NTR8MA&ixlib=rb-4.1.0&q=80&w=1080"
                    width="600"
                    height="600"
                    alt="Consumer App"
                    data-ai-hint="mobile application interface"
                    className="mx-auto aspect-square overflow-hidden rounded-xl object-cover"
                />
            </div>
        </section>

        <section id="pricing" className="w-full py-12 md:py-24 lg:py-32">
            <div className="container px-4 md:px-6">
                <div className="grid gap-10 lg:grid-cols-2">
                    <div className="space-y-4">
                        <h2 className="text-3xl font-bold font-headline tracking-tighter sm:text-4xl md:text-5xl">Simple, Transparent Pricing</h2>
                        <p className="text-muted-foreground md:text-xl/relaxed">
                            No contracts, no commitments, no surprises. Pay as you go and only for the responses you receive.
                        </p>
                        <Button asChild size="lg">
                            <Link href="/signup">Get Started for Free</Link>
                        </Button>
                    </div>
                    <div className="flex flex-col gap-6">
                        <Card>
                            <CardHeader className="flex flex-row items-center justify-between pb-2">
                                <h3 className="text-sm font-medium">For Brands</h3>
                                <DollarSign className="w-4 h-4 text-muted-foreground" />
                            </CardHeader>
                            <CardContent>
                                <div className="text-4xl font-bold">$0.50</div>
                                <p className="text-xs text-muted-foreground">per response, no minimums</p>
                            </CardContent>
                        </Card>
                         <Card>
                            <CardHeader className="flex flex-row items-center justify-between pb-2">
                                <h3 className="text-sm font-medium">For Consumers</h3>
                                <DollarSign className="w-4 h-4 text-muted-foreground" />
                            </CardHeader>
                            <CardContent>
                                <div className="text-4xl font-bold">$0.15 - $0.25</div>
                                <p className="text-xs text-muted-foreground">payout per poll, paid instantly</p>
                            </CardContent>
                        </Card>
                    </div>
                </div>
            </div>
        </section>

        <section id="testimonials" className="w-full py-12 md:py-24 lg:py-32">
          <div className="container px-4 md:px-6">
            <h2 className="text-3xl font-bold font-headline tracking-tighter text-center sm:text-4xl md:text-5xl">
              Loved by Brands & Consumers
            </h2>
            <div className="mx-auto grid max-w-5xl grid-cols-1 gap-6 py-12 sm:grid-cols-1 lg:grid-cols-2">
              <Card>
                <CardContent className="flex flex-col gap-4 p-6">
                  <div className="flex items-center gap-4">
                    <Avatar>
                      <AvatarImage src="https://placehold.co/40x40.png" />
                      <AvatarFallback>SC</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-semibold">Sarah Chen</p>
                      <p className="text-xs text-muted-foreground">Product Manager, TechStart</p>
                    </div>
                  </div>
                  <p className="text-muted-foreground">
                    "We launched our new product concept at 9 AM and had 500 responses by 9:15 AM. Game changer!"
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="flex flex-col gap-4 p-6">
                  <div className="flex items-center gap-4">
                    <Avatar>
                      <AvatarImage src="https://placehold.co/40x40.png" />
                      <AvatarFallback>MR</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="font-semibold">Mike R.</p>
                      <p className="text-xs text-muted-foreground">Verified Consumer</p>
                    </div>
                  </div>
                  <p className="text-muted-foreground">
                    "I've earned $127 this month just answering quick questions during my coffee breaks."
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 bg-primary text-primary-foreground">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold font-headline tracking-tighter md:text-4xl/tight">Ready to Feel the Pulse?</h2>
              <p className="mx-auto max-w-[600px] text-primary-foreground/80 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Join PollPulse today and start making data-driven decisions or earning rewards for your valuable insights.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <Button asChild variant="secondary" size="lg" className="w-full">
                <Link href="/signup">Sign Up Now <ArrowRight className="ml-2 h-4 w-4" /></Link>
              </Button>
            </div>
          </div>
        </section>
      </main>
      <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <p className="text-xs text-muted-foreground">&copy; 2024 PollPulse. All rights reserved.</p>
        <nav className="sm:ml-auto flex gap-4 sm:gap-6">
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Terms of Service
          </Link>
          <Link href="#" className="text-xs hover:underline underline-offset-4" prefetch={false}>
            Privacy
          </Link>
        </nav>
      </footer>
    </div>
  )
}
